apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
spec:
  replicas: 3
  selector:
    matchLabels:
      run: kube
  template:
    metadata:
      labels:
        run: kube
    spec:
      containers:
        - name: demo-kube
          image: sabbottlabs/kube
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: APP_KEY
              value: base64:lEw+ClzTPiys+KL1ye1oWmOj8KBhAJrlKtuyRHQeu2w=
